### ISSUE TITLE
Remove security warning from Chrome

### ISSUE THREAD

**Issue by ToniTornado** [Rexios80/flutter_cors#1]
You can add `--test-type` option as well, that will remove the security warning.

![image](https://user-images.githubusercontent.com/431201/151355510-a4cc17c8-f65c-4c9c-8c52-437543e79948.png)

**Comment by Rexios80** [comment]
Hmmm. At least for me I like knowing that CORS is disabled when that banner is shown.

**Comment by ToniTornado** [comment]
Since it is not my default Chrome instance but only the one controlled by Android Studio for development I dislike the banner more than it helps. But I can definitely live with it. Or maybe make it an optional flag as command line argument to remove it? `--hide-banner`
