### ISSUE TITLE
Can we bypass the CORS Issue for Webview also?

### ISSUE THREAD

**Issue by josuva1211** [Rexios80/flutter_cors#10]
Using webview_flutter package I am trying to load a web application through assets not using website URL. While loading the webview I am getting the CORS issue because my web app makes call to an external API resource. To fix the issue, I have used the flutter_cors package. 

**Error:
I/chromium(14757): [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'TARGET_URL' from origin 'http://localhost:40203/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: http://localhost:40203/asset/en/sign-in**

**Comment by Rexios80** [comment]
No
