### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by rameshboyee-sayukth** [Rexios80/flutter_cors#14]
fluttercors -db -p /path/to/flutter

Nothing to patch in /Users/dharma.jalla/Downloads/flutter/packages/flutter_tools/lib/src/web/chrome.dart
Nothing to patch in /Users/dharma.jalla/Downloads/flutter/packages/flutter_tools/lib/src/drive/web_driver_service.dart
No files patched

**Comment by Rexios80** [comment]
Please provide more details. There is nothing actionable in this issue.

**Comment by Rexios80** [comment]
Closing due to not enough information. Feel free to reopen with more details
