### ISSUE TITLE
Better integrate with fvm

### ISSUE THREAD

**Issue by ToniTornado** [Rexios80/flutter_cors#2]
It would be helpful if I could change the path to the Flutter version that I want to modify. I'm using fvm and there are always multiple versions installed on my system side by side.

An easy solution is to accept the path to the Flutter installation as command line argument like so:

`fluttercors enable ~/fvm/versions/2.8.1`

(and if empty just default to `wich flutter` as done currently)

**Comment by Rexios80** [comment]
Good idea. Should probably do this for https://github.com/Rexios80/flutter_m1_patcher as well.

**Comment by ToniTornado** [comment]
Nice I voted & commented on your answer here https://stackoverflow.com/questions/69274086/how-to-replace-the-bundled-dart-sdk-in-flutter-to-run-natively-on-apple-silicon but I didn't notice that this package is also yours! 😀 So yes, the change is useful for both scripts.
