### ISSUE TITLE
Disable CORS on live website

### ISSUE THREAD

**Issue by Scienticious** [Rexios80/flutter_cors#4]
Hello,
I want to disable CORS on my released flutter build.
CORS are not disabled when I release my flutter web build and deploy it on web hosting.

Any Suggession?

**Comment by Rexios80** [comment]
You can't disable CORS in flutter. CORS is a browser feature. This script is only to disable CORS for local testing. If you have issues with CORS in production you will have to fix those issues some other way. Either by properly setting up your API or using a proxy server.
