### ISSUE TITLE
Not working On chrome Version 103.0.5060.134 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by jaeferjafy** [Rexios80/flutter_cors#5]
![image](https://user-images.githubusercontent.com/85485041/181904606-1512e819-bf49-4a28-acb5-3ba064dfc3db.png)

![image](https://user-images.githubusercontent.com/85485041/181904630-270c2e28-08f4-4370-97a4-7cc5f2cbacc5.png)

**Comment by Rexios80** [comment]
You are testing with the chrome instance flutter launches when you run with `flutter run`?

**Comment by Rexios80** [comment]
Wait... That end message means you ran `fluttercors -e` which _enables CORS checks_ which is the opposite of what you want. You run `fluttercors -d` to disable CORS checks which is what you actually want. If you run the command without `--disable-banner` you should see this banner in chrome:
<img width="1200" alt="Screen Shot 2022-07-30 at 1 43 58 PM" src="https://user-images.githubusercontent.com/7896519/181935465-a9885be1-882a-4010-adb1-3373e86a5952.png">

**Comment by Rexios80** [comment]
Let me know if you still can't figure it out. Everything seems fine on my end.
